services:
  front:
    build:
      context: ./front
    ports:
      - 8090:80
  api:
    platform: wasi/wasm
    runtime: io.containerd.wasmedge.v1
    build:
      context: ./api
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: mysql://root:whalehello@db:3306/mysql
      RUST_BACKTRACE: full
    restart: unless-stopped
  db:
    image: mariadb:10.9
    environment:
      MYSQL_ROOT_PASSWORD: whalehello
